Image upload
maciekkwiet/Bookweb pull request #17
Opened 2021-03-02 20:28 UTC by kamildzierzak

2021-03-03 15:17 UTC, sebslon approved these changes
Widziałem, że działa więc chyba gitarka :) pytanko, widzę, że jest pusta funkcja retrieveImage, została do zaimplementowania?

2021-03-03 15:17 UTC, sebslon commented on api/utils/imageTools.ts
> +import { resolve } from 'bluebird';
Chyba się wkradło :P

2021-03-03 23:12 UTC, maciekkwiet requested changes

2021-03-03 23:12 UTC, maciekkwiet commented on api/utils/imageTools.ts
> +const cloudinary = require('cloudinary');
Nie przeszło: import * as cloudinary from 'cloudinary' ?

2021-03-03 23:12 UTC, maciekkwiet commented on api/utils/imageTools.ts
> +    return result.secure_url;
dajmy po result "?" Zeby nam się to nigdy nie wykrzaczyło

2021-03-03 23:12 UTC, maciekkwiet commented on api/utils/imageTools.ts
> +export function retrieveImage(id: any) {}
Do czego to jest potrzebne?

2021-03-07 08:40 UTC, kamildzierzak commented on api/utils/imageTools.ts
> +const cloudinary = require('cloudinary');
Nie przechodzi

2021-03-07 20:39 UTC, maciekkwiet approved these changes

2021-03-07 20:50 UTC, maciekkwiet commented
Conflicts

2021-03-07 21:06 UTC, merged