Star component
maciekkwiet/Bookweb pull request #55
Opened 2021-03-13 16:20 UTC by wojaneta

closes #31

2021-03-14 14:29 UTC, maciekkwiet approved these changes
Małe poprawki ale poza bardzo dobra robota!

2021-03-14 14:29 UTC, maciekkwiet commented on client/src/Components/Star/Star.stories.tsx
> +  onClick: () => {
Dodaj proszę paczkę @storybook/addon-actions do projektu, z niego zaimportujmy action i wywołanie onClicka będzie wyglądało mniej więcej tak:
onClick: action('onClick')

2021-03-14 14:29 UTC, maciekkwiet commented on client/src/Components/Star/StarRating.tsx
> +  const [rating, setRating] = useState(0);
Wydaje mi się że to będziemy pobierali ze stora, ale na razie może tak chyba zostać, później będziemy zmieniać :D

2021-03-14 14:29 UTC, maciekkwiet commented on client/src/Components/Star/StarRating.tsx
> +              color={ratingValue <= (hover || rating) ? 'C92523' : '#e4e5e9'}
Dodajmy te kolory do theme jeżeli jeszcze nie ma i stąd je zaciągajmy :D

2021-03-14 14:29 UTC, maciekkwiet commented on client/src/Components/Star/StarStyles.tsx
> +export const Input = styled.input`
Dobrze pomyślane, super!

2021-03-14 14:29 UTC, maciekkwiet commented on client/src/Components/Star/__tests__/Star.test.tsx
> +        <div>
Czy ten div jest potrzebny?

2021-03-14 22:18 UTC, KlaraGajaszek requested changes

2021-03-14 22:18 UTC, KlaraGajaszek commented on client/src/App.tsx
> +      <div>
usuń to prosze ja dałam tylko taki przykład nie bedzie nam to tutaj potrzebne

2021-03-14 22:18 UTC, KlaraGajaszek commented on client/src/Components/Star/Star.stories.tsx
> +import { Story } from '@storybook/react';
linijka przerwy po imporcie bibliotek wcałym pliku

2021-03-14 22:18 UTC, KlaraGajaszek commented on client/src/Components/Star/StarRating.tsx
> +              color={ratingValue <= (hover || rating) ? 'C92523' : '#e4e5e9'}
możesz posluzyc sie thema i ostylowac to za omoca style component zeby nie pisac na sztywno kolorow

2021-03-19 16:06 UTC, maciekkwiet approved these changes
Drobne poprawki i mozna mergowac

2021-03-19 16:06 UTC, maciekkwiet commented on client/.storybook/main.js
>    addons: ['@storybook/addon-links', '@storybook/addon-essentials', '@storybook/preset-create-react-app'],
Dodajmy to co jest niżej tutaj

2021-03-19 16:06 UTC, maciekkwiet commented on client/src/Components/Star/Star.stories.tsx
> +import { action } from '@storybook/addon-actions';
To idzie do góry do drugiej linijki
Z tego co wiem, to jest tak że jako pierwsze importujemy jakby pliki z nodeModules a wiec właśnie takie pliki jak teraz w 1 i 5 linijce, a dopiero później pliki od nas z projektu czyli ze sciezka relatywna, tak jak zasugerowała Klara można zrobić przerwę miedzy tymi dwiema częściami, ale często nie jest to błędem(Ja np. nie robię najczęściej), ale zgodnie ze sztuką powinno się robić :D

2021-03-19 16:06 UTC, maciekkwiet commented on client/src/Components/Star/Star.stories.tsx
> +  onClick: action('onClick'),
Dobra robota!

2021-03-21 13:37 UTC, merged