UI checkbox
maciekkwiet/Bookweb pull request #56
Opened 2021-03-14 11:53 UTC by rafalskotnicki

Closes #29

2021-03-14 14:35 UTC, maciekkwiet requested changes

2021-03-14 14:35 UTC, maciekkwiet commented on client/src/Components/Checkbox/Icon.tsx
> +import styled from 'styled-components';
Połączmy te wszystkie style w jeden plik, nazwijmy go CheckoxStyled.tsx

2021-03-14 14:35 UTC, maciekkwiet commented on client/src/Components/Checkbox/VisibleCheckbox.tsx
> +  background: ${(props) => (props.checked ? '#9EB2CD' : '#CB997E')};
Przenieśmy te kolory do theme i importujmy je jako stałe o ile jeszcze ich tam nie ma

2021-03-14 14:35 UTC, maciekkwiet commented on client/src/Components/Checkbox/HiddenCheckbox.tsx
> +  margin: -1px;
Czemu to ma służyć?

2021-03-14 14:35 UTC, maciekkwiet commented on client/src/Components/Checkbox/VisibleCheckbox.tsx
> +    box-shadow: 0 0 0 3px #9eb2cd;
Ten kolor tak samo

2021-03-14 14:35 UTC, maciekkwiet commented on client/src/Components/Checkbox/CheckboxComponent.tsx
> +        <span>Gatunek</span>
Przekazujmy to może z propsa, jako default value może być ten Gatunek

2021-03-14 22:29 UTC, KlaraGajaszek requested changes

2021-03-14 22:29 UTC, KlaraGajaszek commented on client/src/Components/Checkbox/CheckboxComponent.tsx
> +  const handleCheckboxChange = (event) => setChecked(event.target.checked);
może lepiej setChecked(!checked)

2021-03-14 22:29 UTC, KlaraGajaszek commented on client/src/Components/Checkbox/HiddenCheckbox.tsx
> +import styled from 'styled-components';
Normalnie w projektach customowego checkboxa robi sie tak, że daje sie niewidocznego inputa i styluje sie label a w środku jako children przekazuje się ikonnkę, ale dla naszych potrzeb może zostać

2021-03-14 22:29 UTC, KlaraGajaszek commented on client/src/Components/Checkbox/Label.tsx
> +  background: #f2f4f3;
use theme

2021-03-25 19:05 UTC, maciekkwiet approved these changes

2021-03-25 19:05 UTC, maciekkwiet commented on client/src/Components/Checkbox/CheckboxStyles.tsx
> +`;
Woow! Powiem Ci że nigdy nie widziałem czegoś takiego ;p

2021-03-25 19:05 UTC, maciekkwiet commented on client/src/Components/Checkbox/CheckboxStyles.tsx
> +  box-shadow: 0 0 3px 1px #505050;
Może ten kolor z theme?

2021-03-26 13:10 UTC, merged