UI | Zdjęcie #28
maciekkwiet/Bookweb pull request #57
Opened 2021-03-15 08:57 UTC by kamildzierzak

2021-03-15 23:35 UTC, maciekkwiet approved these changes
Małe zmiany

2021-03-15 23:35 UTC, maciekkwiet commented on client/src/App.tsx
> +      <Image src="https://edit.org/images/cat/book-covers-big-2019101610.jpg" alt="book" width="63" height="93" />
Tego width i height nie przekazujemy w propsach :D

2021-03-15 23:35 UTC, maciekkwiet commented on client/src/Components/Image/ImageStyles.tsx
> +`;
To nam w tym przypadku nie jest potrzebne wgl

2021-03-15 23:36 UTC, maciekkwiet commented
@KlaraGajaszek Jakie jest plan na ten komponent? Bo nie za bardzo wiem chyba co on ma robić? Bo z tego co widzę to zostaje czysty HTMLowy selector, więc czy to wgl ma sens?

2021-03-15 23:37 UTC, maciekkwiet requested changes
Na chwilę się wstrzymajmy z mergem tego

2021-03-15 23:47 UTC, KlaraGajaszek requested changes
tak jak nie stylujemy tego komponentu to nie ma sensu go tworzyc bo tak jak Maciek napisal nic nie wnosi, ale jak dodamy style np. cien, lekkie zaokraglenie itd. to wtedy nabiera wiekszego sensu :) Dlatego prosze dodaj do tego sdjecia shadow, jak bedzie wygladac fajnie to mozesz dodac tez zaokraglenia na krawedziach wg uznania :) I nazwij ten komponent jako ShadowImage to wtady zaoszczedzimy Mackowi komentarzy :)

2021-03-19 16:12 UTC, maciekkwiet approved these changes
Jedna drobna poprawka i można mergować

2021-03-19 16:12 UTC, maciekkwiet commented on client/src/Components/ShadowImage/ShadowImageStyles.tsx
> +  height: ${(props) => props.height};
Usuńmy to

2021-03-21 13:35 UTC, merged