Header
maciekkwiet/Bookweb pull request #65
Opened 2021-03-27 17:34 UTC by wojaneta

closes #42 
Header w widoku "niezalogowany" i "zalogowany" użytkownik, bez logiki, dodałam na razie jako komponent (header będziemy mieć na każdym widoku (stronie) i nie wiedziałam do końca gdzie go dodać)
<img width="1280" alt="Screenshot 2021-03-27 at 18 20 02" src="https://user-images.githubusercontent.com/63155419/112728806-50fb2700-8f29-11eb-9ff1-a79ac38fd08c.png">

<img width="1279" alt="Screenshot 2021-03-27 at 18 19 34" src="https://user-images.githubusercontent.com/63155419/112728802-4f316380-8f29-11eb-8f80-21f4bb3ad67f.png">

2021-03-28 22:54 UTC, maciekkwiet requested changes
Kilka poprawek :D
Ale dobra robota!

2021-03-28 22:54 UTC, maciekkwiet commented on client/src/Components/Header/HeaderStyles.tsx
> +font-family: Esteban;
wcięcia

2021-03-28 22:54 UTC, maciekkwiet commented on client/src/Components/Header/HeaderStyles.tsx
> +  // height: 20%;
Usuńmy te komentarze

2021-03-28 22:54 UTC, maciekkwiet commented on client/src/Components/Header/AnonymousDivStyles.tsx
> +  // border: 0;
Kom

2021-03-28 22:54 UTC, maciekkwiet commented on client/src/Components/Header/AnonymousDivStyles.tsx
> +  z-index: 1;
Default chyba że to skądś nadpisujsz to okey :D

2021-03-28 22:54 UTC, maciekkwiet commented on client/src/Components/Header/Header.tsx
> +  }
const LogViev = isLogged ? <LoggedDiv userName="userName" userID="userName" /> : LogView = <AnonymousDiv />

Chyba tak będzie wyglądało troche lepiej :D

2021-03-28 22:54 UTC, maciekkwiet commented on client/src/Components/Header/Header.tsx
> +import { TitleDiv } from './HeaderStyles';
Zróbmy to z 1 importa po przecinku

2021-03-28 22:54 UTC, maciekkwiet commented on client/src/Components/Header/AnonymousDiv.tsx
> +  const [password, setPassword] = useState('');
Czy to jest nam potrzebne?
Wydaje mi sie że generalnie wszystkie dane będą pobierane po kliknięciu w button wyślij więc chyba nie potrzebujemy tego

2021-03-28 22:55 UTC, maciekkwiet commented
Na razie tak jak jest jest okey, jak będziemy sklejać widoki to tutaj coś więcej zrobimy :D

2021-03-30 18:25 UTC, maciekkwiet approved these changes
Drobne poprawki

2021-03-30 18:25 UTC, maciekkwiet commented on client/src/Components/Header/AnonymousDiv.tsx
> +  // const [password, setPassword] = useState('');
To możemy usunąć

2021-03-30 18:25 UTC, maciekkwiet commented on client/src/Components/Header/HeaderStyles.tsx
> +  font-family: Esteban;
Theme

2021-03-30 18:25 UTC, maciekkwiet commented on client/src/Components/Header/HeaderStyles.tsx
> +  color: #3D5A80;
Theme

2021-04-01 16:26 UTC, KlaraGajaszek approved these changes

2021-04-02 19:05 UTC, maciekkwiet commented
Konflikty i merge

2021-04-02 20:05 UTC, merged