Registration form
maciekkwiet/Bookweb pull request #66
Opened 2021-03-28 17:03 UTC by WarmuzWojtek

closes #43 

Kilka wyjaśnień - po stronie api mamy pobieranie przy rejestracji {name, email, password} więc do ustalenia czy zmieniamy w api czy dodajemy name do formularza... nie mam bladego pojęcia czy fetch jest prawidłowo zrobiony no i niestety wciąż nie dałem rady z testem submita - jeśli @KlaraGajaszek lub @maciekkwiet mielibyście kiedyś chwilę na zdzwonkę to bardzo poproszę :)

2021-03-29 16:33 UTC, WarmuzWojtek commented
![Form](https://user-images.githubusercontent.com/65849475/112869091-0e6a5380-90bd-11eb-9867-64f6efaa2a70.jpg)

2021-03-30 18:19 UTC, maciekkwiet requested changes

2021-03-30 18:19 UTC, maciekkwiet commented on client/src/Theme.tsx
> +    danger: 'red',
Jak to red a nie rgb to nie wrucajmy do theme

2021-03-30 18:19 UTC, maciekkwiet commented on client/src/Components/RegistrationForm/RegistrationFormStyles.tsx
> +&:hover {
Wcięcia w całym pliku

2021-03-30 18:19 UTC, maciekkwiet commented on client/src/Components/RegistrationForm/RegistrationForm.tsx
> +            });
Przeróbmy to na axiosa i wynieśmy to przed return będzie duzo bardziej czytelnie

2021-03-30 18:19 UTC, maciekkwiet commented on client/src/Components/RegistrationForm/RegistrationForm.tsx
> +        }}
Czy to jest potrzebne? Wydaje mi sie że to może być default

2021-03-30 18:19 UTC, maciekkwiet commented on client/src/Components/RegistrationForm/RegistrationForm.tsx
> +import { RegistrationFormContainer, RegistrationInput, RegistrationButton, RegistrationFormTitle, RegistrationErrorMessage } from './RegistrationFormStyles';
Jak mamy od 4 importowanych plikow w góre dobrą praktyką jest import każdej od nowej linijki

2021-03-30 18:19 UTC, maciekkwiet commented on client/src/Components/RegistrationForm/RegistrationForm.tsx
> +import * as Yup from 'yup';
Róweniż dobrą praktyką jest import rzeczy z node przed komponentami

2021-03-31 23:01 UTC, KlaraGajaszek approved these changes
Wojtek pozmieniałam trochę, looknij i daj znać co myślisz :)

2021-04-01 16:24 UTC, merged