User acitivity box
maciekkwiet/Bookweb pull request #80
Opened 2021-04-09 14:31 UTC by wojaneta

<img width="1270" alt="Screenshot 2021-04-08 at 22 29 31" src="https://user-images.githubusercontent.com/63155419/114195636-ed252500-9950-11eb-9ad0-8db0fc1670be.png">

2021-04-10 10:56 UTC, maciekkwiet requested changes

2021-04-10 10:56 UTC, maciekkwiet commented on client/src/Theme.tsx
> +    xs: `300px`,
Czy ta zmiana nie psuje innych komponentów?

2021-04-10 10:56 UTC, maciekkwiet commented on client/src/Components/UserAcitivityBox/UserActivityBox.tsx
> +  const readMoreHandler = () => {};
Po co to jest?

2021-04-11 12:16 UTC, KlaraGajaszek approved these changes

2021-04-11 14:34 UTC, merged