Review page
maciekkwiet/Bookweb pull request #82
Opened 2021-04-10 15:51 UTC by kamildzierzak

2021-04-11 12:14 UTC, KlaraGajaszek requested changes

2021-04-11 12:14 UTC, KlaraGajaszek commented on client/src/Pages/AddReviewPage/AddReviewPage.tsx
> +          author={`${bookData?.name ?? ''} ${bookData?.surname ?? ''}`}
@maciekkwiet to jest tu potrzebne ? Wiem że wczoraj mówiłeś o  wartości początkowej  tutaj, ale jak wyśemu "" lub undefinded to wyjdze na to samo chyba

2021-04-11 12:14 UTC, KlaraGajaszek commented on client/src/Pages/AddReviewPage/AddReviewPage.tsx
> +  //token & inter...
tu możesz zmienić tokena to o czym rozmawialiśmy

2021-04-11 12:14 UTC, KlaraGajaszek commented on client/src/Pages/AddReviewPage/AddReviewPage.tsx
> +    axios.post('http://localhost:8080/api/reviews/', reviewInfo).then(() => {
tu też możesz zmienić axiosa i dodać notyfikację

2021-04-11 12:14 UTC, KlaraGajaszek commented on client/src/Pages/AddReviewPage/AddReviewPage.tsx
> +    axios.post('http://localhost:8080/api/reviews/', reviewInfo).then(() => {
a w notyfikacji wyświetl text który przychodzi z backendu

2021-04-11 15:16 UTC, kamildzierzak commented on client/src/Pages/AddReviewPage/AddReviewPage.tsx
> +          author={`${bookData?.name ?? ''} ${bookData?.surname ?? ''}`}
Usunalem wartosc poczatkowa i dziala, ale wyswietla undefined w imieniu i nazwisku autora wiec chyba zostawie te wartosci poczatkowe ze wzgledow estetycznych (☞ﾟヮﾟ)☞

2021-04-13 18:14 UTC, maciekkwiet approved these changes

2021-04-13 18:14 UTC, maciekkwiet commented on client/src/Pages/AddReviewPage/AddReviewPage.tsx
> +    });
Może try catch i async await zeby zachowac spojnosc z reszta?

2021-04-13 18:14 UTC, maciekkwiet commented on client/src/Pages/AddReviewPage/AddReviewPage.tsx
> +  // Czy to tak sie uzywa useSelector by pobrac id ze store?
👍

2021-04-13 18:14 UTC, maciekkwiet commented on api/routes/reviews/reviews.ts
> +  // const userId: number = request.userId;
Remove

2021-04-13 18:15 UTC, maciekkwiet commented on client/src/Pages/AddReviewPage/AddReviewPage.tsx
> +          author={`${bookData?.name ?? ''} ${bookData?.surname ?? ''}`}
Dokładnie o to mi chodziło żeby nie wyświetlało się undefined na froncie :D

2021-04-13 19:30 UTC, merged